services:
  front-end:
    container_name: front-end
    build: .
    image: front-end
    networks:
      - my-network
    ports:
      - 80:80
  
networks:
  my-network:
    name: my-network
    external: true